In [1]:
import numpy as np
from geovectorslib import geod
from boat import get_boat_speed, get_boat_profile
from grib import grib_to_wind_function
from router import move_boat_direct

In [2]:
f_twa, f_tws = grib_to_wind_function('../data/2019122212/2019122212f000')
boat = get_boat_profile('../data/polar-VO70.csv')
f_boat_speed = get_boat_speed

In [3]:
        lats = [10, 20, 30]
        lons = [10, 20, 30]
        hdgs = [11, 12, 13]
        p2 = (lats, lons)

In [4]:
move_boat_direct(lats, lons, hdgs,
    boat, f_boat_speed,
    f_twa, f_tws,
    10, 1
)

[10, 20, 30] [10, 20, 30] [11, 12, 13]
[-6.38356686 -7.3801713  -9.91421866] [34.69935608 44.84736633 25.49043274] [0. 0. 0.]


{'azi1': [11, 12, 13],
 's12': array([0., 0., 0.]),
 'p2': (array([10., 20., 30.]), array([10., 20., 30.])),
 't12': 10}

In [5]:
boat = get_boat_profile('../data/polar-ITA70.csv')

In [6]:
boat

{'func': <scipy.interpolate.interpolate.interp2d at 0x106d67590>,
 'polars': array([[  0.  ,   6.  ,   8.  ,  10.  ,  12.  ,  14.  ,  16.  ,  20.  ],
        [  0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ,   0.  ],
        [ 52.  ,   8.65,  10.53,  11.8 ,  12.57,  13.13,  13.57,  14.88],
        [ 60.  ,   9.37,  11.  ,  12.51,  13.38,  14.04,  14.57,  16.17],
        [ 75.  ,  10.02,  11.74,  13.6 ,  14.98,  15.96,  16.75,  18.41],
        [ 90.  ,  10.5 ,  12.47,  13.91,  15.86,  17.22,  18.21,  19.57],
        [110.  ,  10.34,  12.31,  14.59,  16.17,  17.65,  18.89,  21.74],
        [120.  ,   9.85,  11.62,  13.72,  16.32,  17.89,  19.25,  22.14],
        [135.  ,   8.09,  10.08,  11.36,  13.06,  15.18,  17.34,  22.21],
        [150.  ,   6.61,   8.23,   9.75,  10.92,  12.39,  14.3 ,  18.26]])}

In [4]:
from scipy import stats
import numpy as np

In [100]:
windspeed = np.linspace(0,8,1000000)
# boatspeed = .3 * windspeed**.5 + .2 * np.random.rand(100)
boatspeed = windspeed*2
bin_stat, bin_edges, bin_number = stats.binned_statistic(windspeed,
                boatspeed, statistic='max', bins=np.linspace(0,8,1000))

In [101]:
for i in range(len(bin_edges)-1):
    print(np.where(boatspeed == bin_stat[i]))

(array([1000]),)
(array([2001]),)
(array([3003]),)
(array([4003]),)
(array([5005]),)
(array([6006]),)
(array([7007]),)
(array([8007]),)
(array([9008]),)
(array([10010]),)
(array([11011]),)
(array([12012]),)
(array([13013]),)
(array([14014]),)
(array([15015]),)
(array([16015]),)
(array([17016]),)
(array([18017]),)
(array([19019]),)
(array([20020]),)
(array([21020]),)
(array([22022]),)
(array([23023]),)
(array([24024]),)
(array([25024]),)
(array([26026]),)
(array([27027]),)
(array([28028]),)
(array([29028]),)
(array([30030]),)
(array([31031]),)
(array([32031]),)
(array([33032]),)
(array([34033]),)
(array([35035]),)
(array([36035]),)
(array([37036]),)
(array([38038]),)
(array([39039]),)
(array([40040]),)
(array([41040]),)
(array([42041]),)
(array([43043]),)
(array([44044]),)
(array([45044]),)
(array([46046]),)
(array([47047]),)
(array([48048]),)
(array([49048]),)
(array([50049]),)
(array([51051]),)
(array([52052]),)
(array([53052]),)
(array([54054]),)
(array([55055]),)
(array([56056]),)
(